spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/urna_eletronica
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui

spring.jpa.hibernate.ddl-auto=update