spring.application.name=api

spring.datasource.url=jdbc:postgresql://dpg-d8jji5i8qa3s738jtgp0-a.oregon-postgres.render.com:5432/urna_eletronica_2dnp
spring.datasource.username=urna_eletronica_2dnp_user
spring.datasource.password=qBH1shSLbtz8Ks9RTEpMqHDbLe9stnLy

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect